const input = document.querySelector(".search input");
const button = document.querySelector(".search button");
const cards = document.querySelectorAll(".card");
const output = document.getElementById("ai-output");

const adjectives = [
"Shadow","Hood","Crypto","Moon","Diamond",
"Stealth","Hyper","Quantum","Turbo","Alpha"
];

const suffixes = [
"Coin","AI","Protocol","Labs","Network",
"DAO","Verse","Swap","Finance","Chain"
];

function makeTicker(text){

    return text
    .replace(/[^a-zA-Z0-9 ]/g,"")
    .split(" ")
    .map(word=>word[0])
    .join("")
    .substring(0,5)
    .toUpperCase();

}

function generateToken(prompt){

    const randomAdj =
        adjectives[Math.floor(Math.random()*adjectives.length)];

    const randomSuffix =
        suffixes[Math.floor(Math.random()*suffixes.length)];

    const name = `${randomAdj} ${prompt} ${randomSuffix}`;

    const ticker = makeTicker(name);

    return `
<h2>🚀 ${name}</h2>

<h3>Ticker</h3>
<p>$${ticker}</p>

<h3>Description</h3>
<p>
${name} is an AI-generated meme token concept
built for Robinhood Chain.
Focused on community growth, viral branding,
and long-term ecosystem expansion.
</p>

<h3>Narrative</h3>

<p>

The project combines meme culture,
AI-powered branding,
and Robinhood Chain to create
a recognizable crypto identity.

</p>

<h3>Utility</h3>

<ul>

<li>Community Rewards</li>

<li>Governance</li>

<li>AI Branding</li>

<li>Future Ecosystem</li>

</ul>

<h3>Roadmap</h3>

<ul>

<li>Launch</li>

<li>Community Growth</li>

<li>Marketing</li>

<li>Partnerships</li>

<li>Ecosystem Expansion</li>

</ul>

<h3>First X Post</h3>

<p>

🚀 Introducing <b>${name}</b>

Built on Robinhood Chain.

Powered by community.

Generated by Cloak AI.

#RobinhoodChain

</p>

`;

}

function generate(){

    const prompt=input.value.trim();

    if(prompt===""){

        output.innerHTML="<p>Please enter a prompt.</p>";

        return;

    }

    output.innerHTML=`
<h2 style="color:#00C805;">
🤖 Cloak AI is thinking...
</h2>

<p>
Generating your crypto project...
</p>
`;

    button.disabled=true;

    button.innerHTML="Generating...";

    setTimeout(()=>{

        output.innerHTML=generateToken(prompt);

        button.disabled=false;

        button.innerHTML="Generate";

    },1500);

}

button.onclick=generate;

input.addEventListener("keydown",e=>{

if(e.key==="Enter"){

generate();

}

});

cards.forEach(card=>{

card.onclick=()=>{

input.value=card.querySelector("h3").innerText;

generate();

}

});

const copyBtn=document.getElementById("copyBtn");

if(copyBtn){

copyBtn.onclick=()=>{

navigator.clipboard.writeText(output.innerText);

copyBtn.innerHTML="✅ Copied";

setTimeout(()=>{

copyBtn.innerHTML="📋 Copy";

},1500);

}

}

const downloadBtn=document.getElementById("downloadBtn");

if(downloadBtn){

downloadBtn.onclick=()=>{

const blob=new Blob([output.innerText],{type:"text/plain"});

const link=document.createElement("a");

link.href=URL.createObjectURL(blob);

link.download="cloak-ai-output.txt";

link.click();

}

}
